# Generated by Django 4.2.19 on 2026-02-12 20:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('amount', models.IntegerField(help_text='مبلغ به ریال', validators=[django.core.validators.MinValueValidator(0)])),
                ('accident_date', models.DateField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('approved', 'تأیید'), ('rejected', 'رد'), ('fraud', 'مشکوک به تقلب')], default='pending', max_length=10)),
                ('fraud_score', models.FloatField(db_index=True, default=0)),
                ('fraud_signals', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Insured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_code', models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)])),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(db_index=True, max_length=13)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['national_code', 'phone_number'], name='claims_insu_nationa_6517b0_idx')],
            },
        ),
        migrations.CreateModel(
            name='FraudAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fraud_score', models.FloatField(blank=True, default=0.0, null=True)),
                ('signals', models.JSONField(default=list)),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert', to='claims.claim')),
            ],
        ),
        migrations.AddField(
            model_name='claim',
            name='insured',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='claims.insured'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['insured', 'accident_date'], name='claims_clai_insured_5b1305_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['claim_number'], name='claims_clai_claim_n_0cfa8e_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['status', 'fraud_score'], name='claims_clai_status_63acd7_idx'),
        ),
    ]
