# Generated by Django 4.2.19 on 2026-02-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Claims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraudalert',
            name='fraud_score',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
